### ISSUE TITLE
Completed todo item and edit todo

### ISSUE THREAD

**Issue by vebiolavanessa** [kontenbase/kontenbase#15]
Current Behavior :
Still not implementation checklist and edit todo.

Expect Behavior :
- Checklist implementation
- Edit todo

![image](https://user-images.githubusercontent.com/90052030/146630795-7fa93c5a-fadd-4fb2-86fb-f0753d6b52a7.png)

**Comment by mhaidarhanif** [comment]
This will be up to @aswara to decide if it will be implemented or not implemented.
